from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '625b39c8b293'
down_revision: Union[str, Sequence[str], None] = 'c31e9a4f2f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('highlights', sa.String(), nullable=True))
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('product', 'highlights')
    # ### end Alembic commands ###
