from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2988fe0d154'
down_revision: Union[str, Sequence[str], None] = '2b970ac17c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('short_description', sa.String(length=255), nullable=False))
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('product', 'short_description')
    # ### end Alembic commands ###
